### ISSUE TITLE
Lint errors on clean generation

### ISSUE THREAD

**Issue by Shard** [liquid-state/generator-ls-iwa#2]
Would be nice if we can make sure we don't have lint errors that prevent committing on generation. That main one i found was in the iwa generator for the `src/redux/sagas/index.js` where the linter does not like an empty generator.

I came up with this but an eslint-ignore could probably work too:

```javascript
import { take } from 'redux-saga/effects';

export default function* () {
  yield take('NOTHING');
}
```

**Comment by elsimir** [comment]
Agreed, and Merged.
